import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import {
  ArrowUpRight,
  Bell,
  Bus,
  ChartNoAxesCombined,
  ClipboardCheck,
  GraduationCap,
  LayoutDashboard,
  Receipt,
  Search,
  Settings,
  Sparkles,
  Users,
  Wallet,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { EASE_PREMIUM } from '@/lib/motion'
import { AreaSpark, BarChart, HeatGrid, RingChart } from './Charts'

const NAV = [
  { icon: LayoutDashboard, label: 'Overview' },
  { icon: Users, label: 'Students' },
  { icon: GraduationCap, label: 'Academics' },
  { icon: Receipt, label: 'Fees' },
  { icon: ClipboardCheck, label: 'Attendance' },
  { icon: Bus, label: 'Transport' },
  { icon: ChartNoAxesCombined, label: 'Analytics' },
  { icon: Sparkles, label: 'AI Suite' },
  { icon: Settings, label: 'Settings' },
]

const KPIS = [
  { label: 'Collection this term', value: '₹2.84 Cr', delta: '+12.4%', spark: [22, 30, 26, 38, 34, 46, 43, 58, 62], tone: 'brand' },
  { label: 'Attendance today', value: '96.2%', delta: '+1.8%', spark: [88, 91, 89, 94, 92, 95, 94, 96, 96], tone: 'azure' },
  { label: 'Active students', value: '2,412', delta: '+86', spark: [30, 32, 35, 34, 38, 42, 44, 47, 52], tone: 'aqua' },
  { label: 'Pending dues', value: '₹18.6 L', delta: '−22%', spark: [62, 58, 55, 49, 44, 40, 35, 30, 26], tone: 'brand' },
]

const TONE_STROKE: Record<string, string> = {
  brand: 'var(--color-brand-500)',
  azure: 'var(--color-azure-500)',
  aqua: 'var(--color-aqua-500)',
}

const ACTIVITY = [
  { who: 'Aarav Sharma', what: 'Fee instalment paid', when: 'just now', amount: '₹24,500', tone: 'emerald' },
  { who: 'Grade 8-C', what: 'Attendance marked · 42/44', when: '2m', amount: '95%', tone: 'azure' },
  { who: 'Diya Nair', what: 'Admission confirmed', when: '6m', amount: 'Grade 6', tone: 'brand' },
  { who: 'Bus 12 · Route A', what: 'Reached final stop', when: '11m', amount: 'On time', tone: 'aqua' },
  { who: 'Term-2 Report Cards', what: 'Generated by AI · 318 students', when: '24m', amount: 'Ready', tone: 'brand' },
]

const TONE_DOT: Record<string, string> = {
  emerald: 'bg-emerald-400',
  azure: 'bg-azure-500',
  brand: 'bg-brand-500',
  aqua: 'bg-aqua-400',
}

/**
 * A live, DOM-rendered replica of the SchoolDeck admin console.
 * Rendered rather than screenshotted so it stays crisp at any size,
 * respects the active theme, and can animate on scroll.
 */
export function DashboardUI({
  className,
  compact = false,
}: {
  className?: string
  compact?: boolean
}) {
  const [active, setActive] = useState(0)

  // Auto-play the navigation so the preview feels alive.
  useEffect(() => {
    const id = setInterval(() => setActive((i) => (i + 1) % 4), 3200)
    return () => clearInterval(id)
  }, [])

  return (
    <div
      className={cn(
        'relative flex h-full w-full overflow-hidden rounded-[14px] bg-elevated text-left',
        'border border-[rgb(var(--glass-border)/0.1)]',
        className,
      )}
    >
      {/* ---------------------------------------------------------- Sidebar */}
      <aside
        className={cn(
          'hidden shrink-0 flex-col gap-1 border-r border-[rgb(var(--glass-border)/0.08)] bg-[rgb(var(--surface-muted))] p-3 sm:flex',
          compact ? 'w-[52px]' : 'w-[168px]',
        )}
      >
        <div className="mb-4 flex items-center gap-2 px-1">
          <div className="grid h-6 w-6 shrink-0 place-items-center rounded-[7px] bg-[linear-gradient(135deg,var(--color-brand-600),var(--color-azure-600))]">
            <GraduationCap className="h-3.5 w-3.5 text-white" strokeWidth={2.4} />
          </div>
          {!compact && (
            <span className="font-display text-[11px] font-bold tracking-tight text-strong">
              SchoolDeck
            </span>
          )}
        </div>

        {NAV.map((item, i) => (
          <button
            key={item.label}
            onClick={() => setActive(i)}
            className={cn(
              'flex items-center gap-2.5 rounded-lg px-2 py-[7px] text-[10.5px] font-medium transition-colors duration-300',
              i === active
                ? 'bg-brand-600/12 text-brand-600 dark:text-brand-300'
                : 'text-subtle hover:bg-[rgb(var(--glass-border)/0.06)]',
            )}
          >
            <item.icon className="h-[13px] w-[13px] shrink-0" strokeWidth={2} />
            {!compact && <span className="truncate">{item.label}</span>}
          </button>
        ))}

        {!compact && (
          <div className="mt-auto rounded-xl border border-brand-500/20 bg-brand-600/8 p-2.5">
            <p className="text-[9px] leading-snug font-medium text-strong">AI briefing ready</p>
            <p className="mt-0.5 text-[8.5px] leading-snug text-subtle">3 items need you today</p>
          </div>
        )}
      </aside>

      {/* ------------------------------------------------------------- Main */}
      <div className="flex min-w-0 flex-1 flex-col">
        {/* Topbar */}
        <header className="flex shrink-0 items-center gap-3 border-b border-[rgb(var(--glass-border)/0.08)] px-4 py-2.5">
          <div className="flex min-w-0 flex-1 items-center gap-2 rounded-lg border border-[rgb(var(--glass-border)/0.09)] bg-[rgb(var(--surface-muted))] px-2.5 py-1.5">
            <Search className="h-3 w-3 shrink-0 text-subtle" />
            <span className="truncate text-[10px] text-subtle">
              Search students, fees, staff…
            </span>
            <kbd className="ml-auto hidden shrink-0 rounded border border-[rgb(var(--glass-border)/0.12)] px-1 font-mono text-[8px] text-subtle md:block">
              ⌘K
            </kbd>
          </div>
          <div className="relative">
            <Bell className="h-3.5 w-3.5 text-subtle" />
            <span className="absolute -top-0.5 -right-0.5 h-1.5 w-1.5 rounded-full bg-brand-500" />
          </div>
          <div className="grid h-6 w-6 place-items-center rounded-full bg-[linear-gradient(135deg,var(--color-brand-500),var(--color-azure-600))] font-mono text-[8.5px] font-bold text-white">
            RK
          </div>
        </header>

        {/* Body */}
        <div className="min-h-0 flex-1 overflow-hidden p-3.5">
          <div className="mb-3 flex items-baseline justify-between">
            <div>
              <h3 className="font-display text-[13px] font-semibold text-strong">
                Good morning, Principal
              </h3>
              <p className="text-[9.5px] text-subtle">
                Term 2 · Academic Year 2026-27 · 2,412 students
              </p>
            </div>
            <span className="hidden items-center gap-1.5 rounded-full border border-emerald-500/25 bg-emerald-500/10 px-2 py-0.5 font-mono text-[8.5px] text-emerald-500 sm:inline-flex">
              <span className="h-1 w-1 rounded-full bg-emerald-400" />
              LIVE
            </span>
          </div>

          {/* KPI row */}
          <div className="mb-3 grid grid-cols-2 gap-2.5 lg:grid-cols-4">
            {KPIS.map((kpi, i) => (
              <motion.div
                key={kpi.label}
                initial={{ opacity: 0, y: 14 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.7, delay: i * 0.08, ease: EASE_PREMIUM }}
                className="relative overflow-hidden rounded-xl border border-[rgb(var(--glass-border)/0.08)] bg-[rgb(var(--surface-muted))] p-2.5"
              >
                <p className="truncate text-[8.5px] font-medium tracking-wide text-subtle uppercase">
                  {kpi.label}
                </p>
                <div className="mt-1 flex items-end justify-between gap-1">
                  <span className="font-display text-[15px] leading-none font-bold text-strong">
                    {kpi.value}
                  </span>
                  <span
                    className={cn(
                      'font-mono text-[8.5px] font-semibold',
                      kpi.delta.startsWith('−') ? 'text-emerald-500' : 'text-emerald-500',
                    )}
                  >
                    {kpi.delta}
                  </span>
                </div>
                <div className="mt-1.5 -mx-2.5 -mb-2.5">
                  <AreaSpark
                    points={kpi.spark}
                    height={28}
                    stroke={TONE_STROKE[kpi.tone]}
                    fill={TONE_STROKE[kpi.tone]}
                  />
                </div>
              </motion.div>
            ))}
          </div>

          {/* Charts row */}
          <div className="grid grid-cols-1 gap-2.5 lg:grid-cols-3">
            <div className="rounded-xl border border-[rgb(var(--glass-border)/0.08)] bg-[rgb(var(--surface-muted))] p-3 lg:col-span-2">
              <div className="mb-2.5 flex items-center justify-between">
                <div>
                  <p className="text-[10px] font-semibold text-strong">Fee collection trend</p>
                  <p className="text-[8.5px] text-subtle">Last 12 weeks · all classes</p>
                </div>
                <span className="inline-flex items-center gap-0.5 font-mono text-[8.5px] text-emerald-500">
                  <ArrowUpRight className="h-2.5 w-2.5" />
                  12.4%
                </span>
              </div>
              <div className="h-[74px]">
                <BarChart
                  values={[38, 46, 42, 55, 49, 61, 58, 70, 66, 78, 74, 88]}
                  accentIndex={11}
                />
              </div>
              <div className="mt-2.5 border-t border-[rgb(var(--glass-border)/0.07)] pt-2">
                <p className="mb-1.5 text-[8.5px] font-medium text-subtle">
                  Attendance heatmap · Grade 6–12
                </p>
                <HeatGrid rows={4} cols={22} />
              </div>
            </div>

            <div className="flex flex-col gap-2.5">
              <div className="flex items-center gap-3 rounded-xl border border-[rgb(var(--glass-border)/0.08)] bg-[rgb(var(--surface-muted))] p-3">
                <RingChart value={96} size={64} stroke={6} label="96%" sub="TODAY" />
                <div className="min-w-0">
                  <p className="text-[10px] font-semibold text-strong">Attendance</p>
                  <p className="text-[8.5px] leading-snug text-subtle">
                    2,321 present · 91 absent
                  </p>
                  <p className="mt-1 font-mono text-[8px] text-brand-500">
                    Alerts sent to 91 parents
                  </p>
                </div>
              </div>

              <div className="min-h-0 flex-1 overflow-hidden rounded-xl border border-[rgb(var(--glass-border)/0.08)] bg-[rgb(var(--surface-muted))] p-3">
                <p className="mb-2 text-[10px] font-semibold text-strong">Live activity</p>
                <ul className="space-y-1.5">
                  <AnimatePresence initial={false}>
                    {ACTIVITY.map((a, i) => (
                      <motion.li
                        key={a.who}
                        initial={{ opacity: 0, x: -8 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5, delay: 0.3 + i * 0.09 }}
                        className="flex items-start gap-2"
                      >
                        <span
                          className={cn(
                            'mt-[5px] h-1.5 w-1.5 shrink-0 rounded-full',
                            TONE_DOT[a.tone],
                          )}
                        />
                        <div className="min-w-0 flex-1">
                          <p className="truncate text-[9px] font-medium text-strong">{a.who}</p>
                          <p className="truncate text-[8.5px] text-subtle">{a.what}</p>
                        </div>
                        <span className="shrink-0 font-mono text-[8px] text-subtle">{a.when}</span>
                      </motion.li>
                    ))}
                  </AnimatePresence>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

/* ----------------------------------------------------- Mobile parent app */

export function PhoneUI({ className }: { className?: string }) {
  return (
    <div
      className={cn(
        'relative flex h-full w-full flex-col overflow-hidden rounded-[26px] bg-elevated',
        className,
      )}
    >
      <div className="flex items-center justify-between px-4 pt-3 pb-1 font-mono text-[8px] text-subtle">
        <span>9:41</span>
        <span className="flex gap-1">
          <span className="h-1.5 w-1.5 rounded-full bg-current opacity-60" />
          <span className="h-1.5 w-1.5 rounded-full bg-current opacity-60" />
        </span>
      </div>

      <div className="flex-1 space-y-2.5 overflow-hidden px-3.5 pb-3">
        <div>
          <p className="text-[8px] tracking-wider text-subtle uppercase">Parent portal</p>
          <p className="font-display text-[13px] font-bold text-strong">Aarav Sharma</p>
          <p className="text-[8.5px] text-subtle">Grade 8-C · Roll 14</p>
        </div>

        <div className="rounded-2xl bg-[linear-gradient(135deg,var(--color-brand-600),var(--color-azure-600))] p-3 text-white">
          <p className="text-[8.5px] opacity-80">Next instalment</p>
          <p className="font-display text-[17px] font-bold">₹24,500</p>
          <p className="mt-0.5 text-[8px] opacity-80">Due 5 Nov · Term 2</p>
          <div className="mt-2 rounded-lg bg-white/20 py-1.5 text-center text-[9px] font-semibold backdrop-blur">
            Pay now
          </div>
        </div>

        <div className="grid grid-cols-2 gap-2">
          {[
            { k: 'Attendance', v: '96%' },
            { k: 'Class rank', v: '#4' },
          ].map((s) => (
            <div
              key={s.k}
              className="rounded-xl border border-[rgb(var(--glass-border)/0.09)] bg-[rgb(var(--surface-muted))] p-2"
            >
              <p className="text-[7.5px] tracking-wide text-subtle uppercase">{s.k}</p>
              <p className="font-display text-[13px] font-bold text-strong">{s.v}</p>
            </div>
          ))}
        </div>

        <div className="rounded-xl border border-[rgb(var(--glass-border)/0.09)] bg-[rgb(var(--surface-muted))] p-2.5">
          <p className="mb-1.5 text-[9px] font-semibold text-strong">Today</p>
          {[
            ['Maths', '08:00'],
            ['Science Lab', '09:40'],
            ['English', '11:20'],
          ].map(([subject, time]) => (
            <div key={subject} className="flex justify-between py-[3px]">
              <span className="text-[8.5px] text-body">{subject}</span>
              <span className="font-mono text-[8px] text-subtle">{time}</span>
            </div>
          ))}
        </div>

        <div className="flex items-center gap-2 rounded-xl border border-aqua-500/25 bg-aqua-500/10 p-2.5">
          <Bus className="h-3.5 w-3.5 shrink-0 text-aqua-500" />
          <div className="min-w-0">
            <p className="text-[8.5px] font-semibold text-strong">Bus 12 · 4 stops away</p>
            <p className="text-[8px] text-subtle">Arriving 07:42</p>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-around border-t border-[rgb(var(--glass-border)/0.08)] px-3 py-2">
        {[GraduationCap, Wallet, ChartNoAxesCombined, Bell].map((Icon, i) => (
          <Icon
            key={i}
            className={cn('h-3.5 w-3.5', i === 0 ? 'text-brand-500' : 'text-subtle')}
            strokeWidth={2}
          />
        ))}
      </div>
    </div>
  )
}
